language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
install:
  # Composer
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer --dev install
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
before_script:
  # Database
  - mysql -uroot bluz < tests/dump.sql
  # Directories
  - mkdir .reports
  - chmod a+w ./tests/cache
script:
  # Code style
  - php vendor/bin/phpcs ./src --standard=PSR1 --encoding=utf-8
  - php vendor/bin/phpcs ./src --standard=PSR2 --encoding=utf-8
  - php vendor/bin/phpcs ./tests/src --standard=PSR1 --encoding=utf-8 --ignore=./tests/src/Common/Fixtures,./tests/src/Fixtures
  - php vendor/bin/phpcs ./tests/src --standard=PSR2 --encoding=utf-8 --ignore=./tests/src/Common/Fixtures,./tests/src/Fixtures
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration ./phpunit.xml.dist --coverage-clover=.reports/clover.xml
  # Duplicate code
  #- php vendor/bin/phpcpd --log-pmd .reports/pmd-cpd.xml src
  # Lines of code
  #- php vendor/bin/phploc --log-csv .reports/phploc.csv src
  # works incorrect with latest PHP versions
  # PHP Depend
  #- php vendor/bin/pdepend --jdepend-xml=.reports/jdepend.xml --jdepend-chart=.reports/dependencies.svg --overview-pyramid=.reports/pyramid.svg  ./src
  # Mess detection
  #- php vendor/bin/phpmd ./src text codesize,unusedcode,naming
after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover .reports/clover.xml; fi;'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
